name: "CS497"
coursename: "CS 497"
description: "CS497 Cybersecurity"

url: "//ycpcs.github.io/cs497-spring2019"

kramdown:
    input: GFM
    hard_wrap: false
gems:
    - jekyll-coffeescript
    - jekyll-paginate
    - jekyll-seo-tag
